<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="www/css/cocktails.css">
</head>

<body class="container-fluid">
    <nav>
        <a href="index.php">Accueil</a>
        <h1>Mister Cocktail</h1>
    </nav>

    <main>
        <form action="#" method="POST" enctype="multipart/form-data">
            <div class="row">
                <div class="col-12">
                    <label for="nom" class="form-label">Nom</label>
                    <input type="text" class="form-control" id="nom" name="nom" placeholder="nom du cocktail">
                    <?php echo $errorName ?>
                </div>
                <div class="col-12">
                    <label for="description" class="form-label">Description</label>
                    <textarea name="description" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                    <?php echo $errordescription ?>
                </div>
                <div class="col-12">
                    <label for="urlPhoto" class="form-label">Photo</label>
                    <input type="file" class="form-control" id="urlPhoto" name="urlPhoto" accept="image/png, image/jpeg">
                </div>
                <div class="col-12">
                    <label for="dateConception" class="form-label">Date de conception</label>
                    <input type="date" class="form-control" id="dateConception" name="dateConception" value="2000">
                </div>
                <div class="col-12">
                    <label for="prixMoyen" class="form-label">Prix</label>
                    <input type="number" class="form-control" id="prixMoyen" name="prixMoyen" value="10">
                </div>
                <div class="col-12">
                    <label for="famille" class="form-label">Famille</label>
                    <select class="form-control" name="idFamille">
                        <?php foreach ($listFamille as $row) { ?>
                            <option value="<?php echo $row['id'] ?>"><?php echo $row['nomFamille'] ?></option>
                        <?php } ?>
                    </select>
                </div>
                <div class="label">
                    <?php foreach ($listIngredients as $row) { ?>
                        <label><?php echo $row['nom'] ?></label>
                        <input type="checkbox" name="ingredient[]" value="<?php echo $row['id'] ?>">
                    <?php } ?>
                </div>
                <div class="col-12">
                    <input type="submit" value="Ajouter">
                </div>
            </div>
        </form>
    </main>
</body>

</html>
