<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mister Cocktail</title>
    <!-- Charger CSS de bootstrap, police Montserrat sur Google Fonts et le CSS de l'application -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="www/css/cocktails.css">
</head>
<body class="container-fluid">
    <nav>
        <a href="index.php">Accueil</a>
        <a href="ajouter_cocktail.php">Ajouter</a>
        <a href="back_office.php">Back Office</a>
        <h1>Mister Cocktail</h1>
    </nav>

    <main>
    <table class="table table-striped table-hover">
        <thead class="thead-dark">
            <tr>
                <th>#</th>
                <th>Nom</th>
                <th>Description</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>

             <!-- Listing de tous les cocktails -->
            <?php foreach($listCocktail as $row) { ?>
            <tr>
                <td><?php echo $row['id']; ?></td>
                <td><?php echo $row['nom']; ?></td>
                <td><?php echo $row['description']; ?></td>
                <td><a href="edition_cocktail.php?id=<?php echo $row['id']; ?>">Edition</a></td>
                <td><a href="suppression_cocktail.php?id=<?php echo $row['id']?>">Suppression</a></td>
            </tr>
            <!-- À DE LÀ -->
            <?php } ?>

        </tbody>
    </table>
    
    </main>
</body>
</html>