<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mister Cocktail</title>
    <!-- Charger CSS de bootstrap, police Montserrat sur Google Fonts et le CSS de l'application -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="www/css/cocktails.css">
</head>
<body class="container-fluid">
<?php include './include/menu.php'; ?>

    <main>
        <table class="table table-striped">
            <tr>
                <th>id</th>
                <th>nom</th>
                <th></th>
                <th></th>
            </tr>
            <!-- Listing de tous les cocktails -->
            <?php foreach($listIngredient as $row){ ?>
                <tr>
                   <td><?php echo $row['id'] ?></td> 
                   <td><?php echo $row['nom'] ?></td>
                   <td><a href="edition_ingredient.php?id=<?php echo $row['id'] ?>">Edition</a></td> 
                   <td><a href="suppression_ingredient.php?id=<?php echo $row['id'] ?>">Suppression</a></td> 
                </tr>
            <?php } ?>
        </table>
    </main>
</body>
</html>