<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mister Cocktail</title>
    <!-- Charger CSS de bootstrap, police Montserrat sur Google Fonts et le CSS de l'application -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="www/css/cocktails.css">
</head>
<body class="container-fluid">
    <nav>
        <a href="index.php">Accueil</a>
        <h1>Mister Cocktail</h1>
    </nav>

    <h2>Détails d'un cocktail</h2>
    <img  src="www/images/cocktails/<?php echo $result['urlPhoto']; ?>">
    <ul>
        <!-- Liste des informations sur le cocktail -->
        <li>Nom du cocktail : <?php echo $result['nom']; ?></li>
        <li>Famille : <?php echo $result['nomFamille']; ?></li>
        <li>Description : <?php echo $result['description']; ?></li>
        <li>Prix : <?php echo $result['prixMoyen']; ?> $ €</li>
        <li>Année de conception : <?php echo $result['anneeConception']; ?></li>
    </ul>
</body>
</html>