<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="www/css/cocktails.css">
</head>
<body class="container-fluid">
<?php include './include/menu.php'; ?>

    <main>
        <form action="#" method="POST" enctype="multipart/form-data">
            <div class="row">
                <div class="col-12">
                    <label for="nom" class="form-label">Nom</label>
                    <input type="text" class="form-control" id="nom" name="nom" placeholder="nom de l'ingredient" value="<?php echo $result['nom'] ?>">
                </div>
                <div class="col-12">
                    <input type="submit" value="Modifier">
                </div>
            </div>
        </form>
    </main>
</body>
</html>