<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mister Cocktail</title>
    <!-- Charger CSS de bootstrap, police Montserrat sur Google Fonts et le CSS de l'application -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="www/css/cocktails.css">
</head>
<body class="container-fluid">
    <nav>
        <a href="index.php">Accueil</a>
        <a href="ajouter_cocktail.php">Ajouter</a>
        <h1>Mister Cocktail</h1>
    </nav>

    <main>
        <!-- Listing de tous les cocktails -->
        <?php foreach($listCocktail as $row){ ?>
            <div class="card shadow-sm cocktail">
                <a href="details_cocktail.php?id=<?php echo $row['id']; ?>">
                    <img class="img-fluid" src="www/images/cocktails/<?php echo $row['urlPhoto']; ?>">
                </a>
            <div class="card-body">
              <p class="card-text"><?php echo $row['nom']; ?></p>
              <p class="card-text"><?php echo $row['description']; ?></p>
            </div>
          </div>
        <?php } ?>
    </main>
</body>
</html>