<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mister Cocktail</title>
    <!-- Charger CSS de bootstrap, police Montserrat sur Google Fonts et le CSS de l'application -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="www/css/cocktails.css">
</head>
<body class="container-fluid">
    <table>
        <tr>
            <td colspan="2">
                Etes vous sur de vouloir supprimer : <?php echo $result['nom'] ?>
            </td>
        </tr>
        <tr>
            <td>
                <a href="backoffice.php">
                    <button value="Annuler">Annuler</button>
                </a>
            </td>
            <td>
                <form action="#" method="post">
                    <input type="hidden" name="id" value="<?php echo $result['idCocktail'] ?>">
                    <input type="submit" value="Confirmer">
                </form>
            </td>
        </tr>
    </table>
    
    
    
</body>
</html>